services:
  tax-agent:
    build:
      context: .
      dockerfile: ./api.dockerfile
    image: tax-agent:latest
    container_name: tax_agent_container
    ports:
      - 8086:8086
    command: uvicorn api.main:app --host 0.0.0.0 --port 8086 --reload --log-config=log_config.yaml
    env_file:
      - .env
    networks:
      - tax-agent-network
  tax-agent-ui:
    build:
      context: .
      dockerfile: ./api.dockerfile
    image: tax-agent:latest
    container_name: tax_agent_ui_container
    ports:
      - 80:80
    command: uvicorn ui.app:app --host 0.0.0.0 --port 80 --reload --log-config=log_config.yaml

    env_file:
      - .env
    networks:
      - tax-agent-network

networks:
  tax-agent-network:
    external: false
